<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');


/*
 * Digunakan Untuk Infinte Scroll
 */
$config['base_url'] = '';
$config['total_rows'] = 0;
$config['per_page'] = 25;
$config['use_page_numbers'] = true;

/* 
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] 	= 'start';
$config['full_tag_open'] 			= '<nav><ul class="pagination" style="margin-top:0px">';
$config['full_tag_close'] 			= '</ul></nav>';

$config['first_link'] = 'First';
//$config['first_link']           	= '<i class="fa fa-fast-backward text-maroon"></i>';
$config['first_tag_open'] 			= '<li>';
$config['first_tag_close'] 			= '</li>';

$config['last_link'] = 'Last';
//$config['last_link']            	= '<i class="fa fa-fast-forward text-maroon"></i>';
$config['last_tag_open'] 			= '<li>';
$config['last_tag_close'] 			= '</li>';

//$config['next_link'] = 'Next';
$config['next_link']            	= '<i class="fa fa-step-forward text-green"></i>';
$config['next_tag_open'] 			= '<li>';
$config['next_tag_close'] 			= '</li>';

//$config['prev_link'] = 'Prev';
$config['prev_link']            	= '<i class="fa fa-step-backward text-green"></i>';
$config['prev_tag_open'] 			= '<li>';
$config['prev_tag_close'] 			= '</li>';

$config['cur_tag_open'] 			= '<li class="active"><a>';
$config['cur_tag_close'] 			= '</a></li>';

$config['num_tag_open'] 			= '<li>';
$config['num_tag_close'] 			= '</li>';


/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-08 08:17:41 */
/* http://harviacode.com */